export const GET_CURRENT_LOADS_REQUEST = 'GET_CURRENT_LOADS/REQUEST';
export const GET_CURRENT_LOADS_SUCCESS = 'GET_CURRENT_LOADS/SUCCESS';
export const GET_CURRENT_LOADS_FAILURE = 'GET_CURRENT_LOADS/FAILURE';

export const ADD_LOAD_REQUEST = 'ADD_LOAD/REQUEST';
export const ADD_LOAD_SUCCESS = 'ADD_LOAD/SUCCESS';
export const ADD_LOAD_FAILURE = 'ADD_LOAD/FAILURE';
