export const GET_CURRENT_LOADS_REQUEST = 'GET_CURRENT_LOADS/REQUEST';
export const GET_CURRENT_LOADS_SUCCESS = 'GET_CURRENT_LOADS/SUCCESS';
export const GET_CURRENT_LOADS_FAILURE = 'GET_CURRENT_LOADS/FAILURE';

export const ADD_LOAD_REQUEST = 'ADD_LOAD/REQUEST';
export const ADD_LOAD_SUCCESS = 'ADD_LOAD/SUCCESS';
export const ADD_LOAD_FAILURE = 'ADD_LOAD/FAILURE';

export const GET_USERS_REQUEST = 'GET_USERS/REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS/SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS/FAILURE';

export const ADD_USER_REQUEST = 'ADD_USER/REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER/SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER/FAILURE';
