export default [
  {
    id: 1,
    load: 600,
    container: 200,
    reservation: '$100',
    appointmentTime: '12 Jul - 2:00 PM',
    returnRail: 12,
    pull: 6,
    emptyDropped: 0,
    loadedRail: 12,
    puName: 'Ali',
    driver: 'Micky',
    Rep: 'Donald',
  },
  {
    id: 2,
    load: 360,
    container: 200,
    reservation: '$120',
    appointmentTime: '1 May - 5:30 PM',
    returnRail: 12,
    pull: 6,
    emptyDropped: 0,
    loadedRail: 12,
    puName: 'Mohamed',
    driver: 'Stack',
    Rep: 'Man',
  },
  {
    id: 3,
    load: 789,
    container: 200,
    reservation: '$250',
    appointmentTime: '6 Dec - 9:00 AM',
    returnRail: 12,
    pull: 6,
    emptyDropped: 0,
    loadedRail: 12,
    puName: 'Inu',
    driver: 'Jasa',
    Rep: 'Naru',
  },
];
